<?php
// tässä tiedostossa filut, jotka installer.phar tarvitsee toimiakseen
return function ($backendSrcPath, $pikeSrcPath, $buildAssetsPath, $backendPath) { return [
    $pikeSrcPath . 'Auth/Crypto.php',
    $pikeSrcPath . 'Db.php',
    $pikeSrcPath . 'FileSystem.php',
    $pikeSrcPath . 'FileSystemInterface.php',
    $pikeSrcPath . 'GenericArray.php',
    $pikeSrcPath . 'PikeException.php',
    $pikeSrcPath . 'Request.php',
    $pikeSrcPath . 'Response.php',
    $pikeSrcPath . 'Template.php',
    $pikeSrcPath . 'Translator.php',
    $pikeSrcPath . 'Validator.php',
    $backendPath . 'vendor/altorouter/altorouter/AltoRouter.php',
    $backendSrcPath . 'Common/LoggerAccess.php',
    $backendSrcPath . 'Common/ErrorLogLogger.php',
    $backendSrcPath . 'Content/DAO.php',
    $backendSrcPath . 'Content/DMO.php',
    $backendSrcPath . 'ContentType/ContentTypeCollection.php',
    $backendSrcPath . 'ContentType/ContentTypeDef.php',
    $backendSrcPath . 'ContentType/ContentTypeMigrator.php',
    $backendSrcPath . 'ContentType/ContentTypeValidator.php',
    $backendSrcPath . 'ContentType/FieldCollection.php',
    $backendSrcPath . 'Installer/InstallerApp.php',
    $backendSrcPath . 'Installer/InstallerControllers.php',
    $backendSrcPath . 'Installer/Installer.php',
    $backendSrcPath . 'Installer/main-view.tmpl.php',
    $backendSrcPath . 'Packager/Packager.php',
    $backendSrcPath . 'Packager/PackageStreamInterface.php',
    $backendSrcPath . 'Packager/PlainTextPackageStream.php',
    $backendSrcPath . 'Website/SiteConfig.php',
    $backendSrcPath . 'Website/UrlMatcherCollection.php',
    $backendSrcPath . 'Website/UrlMatcher.php',
    $buildAssetsPath . 'Psr4Autoloader.php',
    $buildAssetsPath . 'LoggerInterface.php',
]; };