<?php
// tässä tiedostossa filut, jotka installer.phar tarvitsee toimiakseen
return function ($backendSrcPath, $buildAssetsPath, $backendPath) { return [
    $backendSrcPath . 'Framework/Db.php',
    $backendSrcPath . 'Framework/FileSystem.php',
    $backendSrcPath . 'Framework/FileSystemInterface.php',
    $backendSrcPath . 'Framework/GenericArray.php',
    $backendSrcPath . 'Framework/Request.php',
    $backendSrcPath . 'Framework/Response.php',
    $backendSrcPath . 'Framework/Template.php',
    $backendSrcPath . 'Framework/Validator.php',
    $backendSrcPath . 'Common/LoggerAccess.php',
    $backendSrcPath . 'Common/ErrorLogLogger.php',
    $backendSrcPath . 'Common/RadException.php',
    $backendSrcPath . 'Content/DAO.php',
    $backendSrcPath . 'Content/DMO.php',
    $backendSrcPath . 'ContentType/ContentTypeCollection.php',
    $backendSrcPath . 'ContentType/ContentTypeDef.php',
    $backendSrcPath . 'ContentType/ContentTypeMigrator.php',
    $backendSrcPath . 'ContentType/ContentTypeValidator.php',
    $backendSrcPath . 'ContentType/FieldCollection.php',
    $backendSrcPath . 'Installer/InstallerApp.php',
    $backendSrcPath . 'Installer/InstallerControllers.php',
    $backendSrcPath . 'Installer/Installer.php',
    $backendSrcPath . 'Installer/main-view.tmpl.php',
    $backendSrcPath . 'Website/SiteConfig.php',
    $backendSrcPath . 'Website/UrlMatcherCollection.php',
    $backendSrcPath . 'Website/UrlMatcher.php',
    $buildAssetsPath . 'Psr4Autoloader.php',
    $buildAssetsPath . 'LoggerInterface.php',
    $backendPath . 'vendor/altorouter/altorouter/AltoRouter.php',
]; };